### ISSUE TITLE
no update after shanghai master

### ISSUE THREAD

**Issue by MarvellousMili** [Ashinch/vct-cn-calendar-subscription#1]
能否加入第二赛段~~谢谢~~

**Comment by Ashinch** [comment]
[v1.3.0: Welcome to VCT CN Evolution Series Act 2: Selection](https://github.com/Ashinch/vct-cn-calendar-subscription/releases/tag/1.3.0)

已添加，大师赛现场后遗症，最近没怎么看，忘记了。
